### ISSUE TITLE
Integration Ordering: Astro-compress + Astro-critters

### ISSUE THREAD

**Issue by PapiPeppers** [Playform/astro-compress#23]
Seeing that integrations are run in the order listed in the config file, what's the recommended ordering of the compress and critters integrations if we have both in our project?

Astro Docs Reference: https://docs.astro.build/en/reference/integrations-reference/#integration-ordering

**Comment by NikolaRHristov** [comment]
Generally, it would be wise to do the compression last. I'll make a few benchmarks and get back to you.

**Comment by PapiPeppers** [comment]
Ok thanks. I'll test it out as well.
