### ISSUE TITLE
Unexpected behaviour. 

### ISSUE THREAD

**Issue by The-Real-Thisas** [Playform/astro-compress#25]
For some reason it insists on removing `type="text"` on inputs.

Now while I understand why it may do this as if your not specifying it as anything specific the generic fallback is text, but in my case it leads to this pretty annoying css bug for my contact page. 

---

## With Compress Active:

<img width="1026" alt="Screenshot 2022-08-28 at 9 14 22 PM" src="https://user-images.githubusercontent.com/59698123/187086331-e2c2ba23-271c-45a7-9b7c-f243e6300bad.png">

```html
    <div class="col-12">
        <label class="js-input-group">Name <input data-required="" name="name" placeholder="Fill in your name" /> <span class="form__error"></span></label>
    </div>
    <div class="col-12">
        <label class="js-input-group">Email <input data-required="" name="email" placeholder="Fill in your email" /> <span class="form__error"></span></label>
    </div>
```

## Without Compress:

<img width="995" alt="Screenshot 2022-08-28 at 9 15 35 PM" src="https://user-images.githubusercontent.com/59698123/187086392-6e5a11b8-a5f3-4446-8d04-4976e8bc619f.png">

```html
    <div class="col-12">
        <label class="js-input-group">
            Name
            <input type="text" name="name" data-required="" placeholder="Fill in your name" />
            <span class="form__error"></span>
        </label>
    </div>

    <div class="col-12">
        <label class="js-input-group">
            Email
            <input type="text" name="email" data-required="" placeholder="Fill in your email" />
            <span class="form__error"></span>
        </label>
    </div>
```

---

I'm not really sure why it does this as I don't really see it doing much to reduce size.

Would it be possible to make this opt-out or opt-in in the config ?

**Comment by NikolaRHristov** [comment]
You can try to remove `removeRedundantAttributes` from the settings in astro-compress:

`astro.config.ts`

```ts
import type { AstroUserConfig } from "astro";
import compress from "astro-compress";

export default (): AstroUserConfig => {
	return {
		integrations: [
			compress({
				html: {
					removeRedundantAttributes: false
				},
			}),
		],
	};
};
```

This is because the default value for the type attribute on an input element is text and is redundant.

**Comment by The-Real-Thisas** [comment]
Ahhh right, this helped fix that issue.

**Comment by The-Real-Thisas** [comment]
Thank you @NikolaRHristov

**Comment by NikolaRHristov** [comment]
np
